on:
  workflow_call:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install -r requirements.txt
          pip install -e ./extract
          python -m pytest
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install -r requirements.txt
          pip install -e ./extract
          pylint --fail-under=6 $(git ls-files '*.py')
