on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    name: test
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v33
      - run: |
          pip install -r requirements.txt
          pytest
  linting:
    name: linting
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v33
      - run: |
          pip install -r requirements.txt
          pylint --fail-under=8 *.py
